# Generated by Django 3.0.5 on 2020-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='world',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('total_cases', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
            ],
        ),
    ]
